[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
optimizer = true
optimizer_runs = 200

# Remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

[rpc_endpoints]
jovay_testnet = "${JOVAY_TESTNET_RPC_URL}"
jovay_mainnet = "${JOVAY_MAINNET_RPC_URL}"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
